Repository Kunstmaan/KunstmaanBundlesStandardEdition, pull requests merged in 2018-06, with the labels that each got.

#263 [Travis] Refactor travis build config and implement extra features/checks
  .travis.yml
  .travis/after_failure.sh
  .travis/before_install.sh
  .travis/before_script.sh
  .travis/install.sh
  .travis/script.sh
  behat.yml
Labels: Enhancement, Target audience: Developers

#260 [Demo] demo standardedition in a docker container
  docker_demo/Dockerfile
  docker_demo/config_docker.yml
  docker_demo/docker-compose.yml
  docker_demo/run.sh
Labels: Enhancement, Feature, Target audience: Developers

#267 [Config][Composer] Remove assetic from kernel and config + updated composer
  app/AppKernel.php
  app/config/config.yml
  app/config/config_base.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  composer.json
  composer.lock
Labels: Bugfix, Deprecation, Priority: High, Target audience: Developers

#266 [Travis] Update deps on cron runs
  .travis/before_script.sh
Labels: Bugfix, Config, Target audience: Developers
