Repository Kunstmaan/KunstmaanBundlesStandardEdition, pull requests merged in 2018-04, with the labels that each got.

#257 [Config] added fos user required email parameters
  app/config/config.yml
  app/config/parameters.yml.dist
Labels: Bugfix, Config

#258 [Travis] fix travis config for bundles V5
  .travis.yml
  .travis/after_failure.sh
  .travis/build/.gitkeep
  app/AppKernel.php
  behat.yml
  composer.json
  composer.lock
Labels: Bugfix, Config, Critical, Priority: High

#259 [Tests] Upload screenshots of failed behat tests
  .travis.yml
  .travis/after_failure.sh
  composer.lock
Labels: Bugfix
